config/routes.rb
Rails.application.routes.draw do
  root "reviews#new"

  resources :decks do
    member do
      put "set_default"
    end
  end

  resources :cards
  resources :reviews, only: [:new, :create]
  resources :user_sessions, path: :login, only: [:create]

  # Registration and authentication
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"
  get "signup" => "registration#new"
  post "signup" => "registration#create"

  # OAuth authorization
  get "oauth/callback" => "oauths#callback"
  post "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  # User profile
  get "profile" => "user_profile#show"
  get "profile/edit" => "user_profile#edit", :as => :edit_profile
  patch "profile" => "user_profile#update"
  delete "profile" => "user_profile#destroy"
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :cards, dependent: :destroy

  validates :title, presence: true
  validates_associated :user
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, except: [:index, :new, :create]

  def index
    @decks = current_user.decks
  end

  def show
    @cards = @deck.cards
  end

  def new
    @deck = Deck.new
  end

  def edit
  end

  def create
    @deck = current_user.decks.new(deck_params)
    if @deck.save
      redirect_to decks_path
    else
      render "new"
    end
  end

  def update
    if @deck.update(deck_params)
      redirect_to decks_path
    else
      render "edit"
    end
  end

  def destroy
    @deck.destroy
    redirect_to decks_path
  end

  def set_default
    current_user.update_attributes(default_deck_id: params[:id])
    redirect_to profile_path
  end

  private

  def deck_params
    params.require(:deck).permit(:title)
  end

  def set_deck
    @deck = current_user.decks.find(params[:id])
  end
end

app/views/decks/_form.html.erb
<%= simple_form_for deck do |f| %>

  <% if deck.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(deck.errors.count, "error") %> prohibited
        this deck from being saved:
      </h2>
      <ul>
        <% deck.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title, as: :string %>
  <%= f.button :submit %>
<% end %>

app/views/decks/edit.html.erb
<%= render 'form', deck: @deck %>

<%= link_to "Set as default", set_default_deck_path(@deck) %>

app/views/decks/index.html.erb
<h3>Колоды (<%= @decks.count %>)</h3>

<table width="100%">
  <tr>
    <th>Название</th>
    <th>Карточек</th>
    <th>Для просмотра</th>
  </tr>

  <% @decks.each do |deck| %>
    <tr>
      <td><%= link_to deck.title, deck_path(deck) %></td>
      <td><%= deck.cards.count %></td>
      <td><%= deck.cards.for_review.count %></td>
      <td><%= link_to 'Редактировать', edit_deck_path(deck) %></td>
      <td><%= link_to 'Удалить', deck_path(deck), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/decks/new.html.erb
<%= render 'form', deck: @deck %>

app/views/decks/show.html.erb
<h3><%= @deck.title %> (<%= @cards.count %>)</h3>

<table width="100%">
  <tr>
    <th>Original</th>
    <th>Translated</th>
    <th>Image</th>
    <th>Review</th>
  </tr>

  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= image_tag card.image.url(:thumb) %></td>
      <td><%= card.review_date.strftime("%d/%m/%Y") %></td>
      <td><%= link_to "Edit", edit_card_path(card) %></td>
      <td><%= link_to "Remove", card_path(card), method: :delete %></td>
    </tr>
  <% end %>
</table>