config/routes.rb
Rails.application.routes.draw do
  root "reviews#new"

  resources :decks do
    member do
      put "set_default"
    end
  end

  resources :cards
  resources :reviews, only: [:new, :create]
  resources :user_sessions, path: :login, only: [:create]

  # Registration and authentication
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"
  get "signup" => "registration#new"
  post "signup" => "registration#create"

  # OAuth authorization
  get "oauth/callback" => "oauths#callback"
  post "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  # User profile
  get "profile" => "user_profile#show"
  get "profile/edit" => "user_profile#edit", :as => :edit_profile
  patch "profile" => "user_profile#update"
  delete "profile" => "user_profile#destroy"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @card = current_user.cards_for_review.first
  end

  def create
    @card = Card.find(review_params[:card_id])
    if @card.review(review_params[:answer])
      flash[:success] = "Правильно!"
    else
      flash[:danger] = "Неправильно!"
    end
    redirect_to root_url
  end

  protected

  def review_params
    params.require(:review).permit(:card_id, :answer)
  end
end

app/views/reviews/_form.html.erb
<%= simple_form_for :review, url: reviews_path  do |f| %>
  <%= f.hidden_field :card_id, value: card.id %>
  <div align="center">
    <%= image_tag card.image.url(:medium) %>
    <p><%= card.translated_text %></p>
  </div>
  <%= f.input :answer %>
  <%= f.button :submit, "Проверить" %>
<% end %>

app/views/reviews/new.html.erb
<% if @card %>
  <%= render 'form', card: @card %>
<% else %>
  <p> Нет карточек для просмотра. </p>
<% end %>