config/routes.rb
Rails.application.routes.draw do
  root "reviews#new"

  resources :decks do
    member do
      put "set_default"
    end
  end

  resources :cards
  resources :reviews, only: [:new, :create]
  resources :user_sessions, path: :login, only: [:create]

  # Registration and authentication
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"
  get "signup" => "registration#new"
  post "signup" => "registration#create"

  # OAuth authorization
  get "oauth/callback" => "oauths#callback"
  post "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  # User profile
  get "profile" => "user_profile#show"
  get "profile/edit" => "user_profile#edit", :as => :edit_profile
  patch "profile" => "user_profile#update"
  delete "profile" => "user_profile#destroy"
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  def show
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to profile_path, notice: "User was successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    current_user.destroy
    redirect_to root_path, notice: "User was successfully destroyed!"
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/views/user_profile/_form.html.erb
<%= simple_form_for current_user, url: profile_path do |f| %>

  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(current_user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% current_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :email, as: :string %>
  <%= f.input :password %>
  <%= f.button :submit %>
<% end %>

app/views/user_profile/edit.html.erb
<h3>Edit profile</h3>

<%= render "form" %>

<%= link_to 'Link GitHub account', auth_at_provider_path(provider: :github) %>

app/views/user_profile/show.html.erb
<h3>User profile</h3>

<p>E-mail: <%= current_user.email %></p>
<p>Decks: <%= current_user.decks.count %></p>
<p>Default deck:
<% if current_user.default_deck %>
  <%= current_user.default_deck.title %>
<% else %>
  no default deck
<% end %>
</p>


<%= link_to "Edit", edit_profile_path %> |
<%= link_to "Destroy", profile_path, method: :delete %>