config/routes.rb
Rails.application.routes.draw do
  root "reviews#new"

  resources :decks do
    member do
      put "set_default"
    end
  end

  resources :cards
  resources :reviews, only: [:new, :create]
  resources :user_sessions, path: :login, only: [:create]

  # Registration and authentication
  get "login" => "user_sessions#new"
  get "logout" => "user_sessions#destroy"
  get "signup" => "registration#new"
  post "signup" => "registration#create"

  # OAuth authorization
  get "oauth/callback" => "oauths#callback"
  post "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  # User profile
  get "profile" => "user_profile#show"
  get "profile/edit" => "user_profile#edit", :as => :edit_profile
  patch "profile" => "user_profile#update"
  delete "profile" => "user_profile#destroy"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<section id="container">

  <header class="clearfix">
    <h1>Флэшкарточкер</h1>
  </header>

  <nav class="navbar navbar-default">
    <a class="navbar-brand" href="/">FlashCard</a>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Колоды", decks_path %></li>
        <li><%= link_to "Добавить колоду", new_deck_path %></li>
        <li><%= link_to "Добавить карту", new_card_path%></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <%= link_to "Logout", logout_path, class: "btn btn-default navbar-btn" %>
          <p class="navbar-text">
            Signed in as <%= link_to current_user.email, profile_path %>
          </p>
        <% else %>
          <%= link_to "Sign Up", signup_path, class: "btn btn-default navbar-btn" %>
        <% end %>
      </ul>
    </div>
  </nav>

  <p style="font-size: 22px;">
    Первый в мире удобный менеджер флеш-карточек. Именно так.
  </p>

  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %>" role="alert">
      <%= message %>
    </div>
  <% end %>

  <%= yield %>

</section>
</body>

</html>